Matrix.map
YaccConstructor/GraphBLAS-sharp pull request #68
Opened 2023-03-21 20:06 UTC by artemiipatov

## Proposed Changes

Matrix.map

## Types of changes

What types of changes does your code introduce to GraphBLAS-sharp?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Build and tests pass locally
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-03-21 21:00 UTC, IgorErin requested changes
Could we generalize some functions and logically separate them?

2023-03-22 07:40 UTC, gsvgit commented on tests/GraphBLAS-sharp.Tests/Matrix/Map.fs
> +      let addFloat64Q =
I guess, these functions can be generalized and placed [here](https://github.com/YaccConstructor/GraphBLAS-sharp/blob/dev/src/GraphBLAS-sharp.Backend/Quotes/Arithmetic.fs)

2023-03-23 06:18 UTC, gsvgit commented on src/GraphBLAS-sharp.Backend/GraphBLAS-sharp.Backend.fsproj
> +    <Compile Include="Quotes\BinSearch.fs" />
Path style.

2023-03-23 06:18 UTC, gsvgit commented on src/GraphBLAS-sharp.Backend/Quotes/Arithmetic.fs
> +    let inline mkOpWithConst zero op constant =
I think we should have two versions because non-commutative operations exist.

2023-03-23 06:18 UTC, gsvgit commented on src/GraphBLAS-sharp.Backend/Quotes/BinSearch.fs
> +    let searchInRange<'a> =
Doc comments required.

2023-03-24 15:44 UTC, IgorErin commented on tests/GraphBLAS-sharp.Tests/Matrix/Map.fs
> +      createTestMap case 0.0f ((*) 10.0f) Utils.float32IsEqual (ArithmeticOperations.mulLeftConst 0.0f 10.0f) Matrix.map
We can pass zero, constant and both functions once to the `createTestMap`. So as not to write them twice

2023-03-25 10:59 UTC, IgorErin requested changes

2023-03-25 10:59 UTC, IgorErin commented on src/GraphBLAS-sharp.Backend/Quotes/BinSearch.fs
> +    let searchCOO<'a> =
Maybe we'll call this function `byKey2D`, since the word `search` is present in the module name.

2023-03-25 10:59 UTC, IgorErin commented on tests/GraphBLAS-sharp.Tests/Matrix/Map.fs
> +
Integers must be supported by the operation. Could you add tests to this

2023-03-25 13:47 UTC, gsvgit commented
Can you resolve conflicts caused by merging of previous request?

2023-03-25 17:25 UTC, IgorErin approved these changes

2023-03-25 17:36 UTC, merged